language: python
python:
  - "3.4"
install:
  - pip install PyYAML
  - pip install flexmock
  - pip install pytest-cov coveralls
script: py.test -vv tests --cov journal_brief
sudo: false
notifications:
  email: false
after_success: "coveralls"
